short_my_url_baby/urls.py
from django.contrib import admin
from django.urls import path

from shortener.views import (
    HomeView,
    handler404,
    handler500,
    link_details,
    link_redirect,
)

handler404 = handler404
handler500 = handler500

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home-view"),
    path("<str:link_id>/info", link_details, name="link-details-view"),
    path("<str:link_id>", link_redirect, name="link-redirect-view"),
]

shortener/models.py
from django.db import models

from . import friendly_id


class Link(models.Model):
    url = models.URLField(max_length=2056)
    link_id = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.url} - {self.link_id}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.id and not self.link_id:
            self.link_id = friendly_id.encode(self.id)
            self.save()

shortener/forms.py
from django import forms

from .models import Link


class LinkModelForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ["url"]
        labels = {"url": ""}


class LinkInfoForm(forms.Form):
    url = forms.URLField(disabled=True, label=False)

shortener/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import View

from .forms import LinkInfoForm, LinkModelForm
from .models import Link


class HomeView(View):
    form_class = LinkModelForm
    initial = {"url": "http://"}
    template_name = "shortener/home.html"

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            instance = form.save()
            return redirect("link-details-view", link_id=instance.link_id)
        return render(request, self.template_name, {"form": form})


def link_details(request, link_id):
    instance = get_object_or_404(Link, link_id=link_id)
    link = reverse("link-redirect-view", kwargs={"link_id": link_id})
    host = request.get_host()
    form = LinkInfoForm(initial={"url": host + link})
    messages.info(request, instance.url)
    context = {"form": form}
    return render(request, "shortener/link_details.html", context)


def link_redirect(request, link_id):
    instance = get_object_or_404(Link, link_id=link_id)
    return HttpResponseRedirect(instance.url)


def handler404(request):
    messages.error(request, "Error 404")
    return render(request, "shortener/base.html", status=404)


def handler500(request):
    messages.error(request, "Error 500")
    return render(request, "shortener/base.html", status=500)

shortener/templates/shortener/base.html
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <style>
        /* Source: https://getbootstrap.com/docs/4.0/examples/cover/ */
        /*
         * Globals
         */

        /* Links */
        a,
        a:focus,
        a:hover {
          color: #fff;
        }

        /* Custom default button */
        .btn-secondary,
        .btn-secondary:hover,
        .btn-secondary:focus {
          color: #333;
          text-shadow: none; /* Prevent inheritance from `body` */
          background-color: #fff;
          border: .05rem solid #fff;
        }


        /*
         * Base structure
         */

        html,
        body {
          height: 100%;
          background-color: #333;
        }

        body {
          display: -ms-flexbox;
          display: -webkit-box;
          display: flex;
          -ms-flex-pack: center;
          -webkit-box-pack: center;
          justify-content: center;
          color: #fff;
          text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
          box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
        }

        .cover-container {
          max-width: 42em;
        }


        /*
         * Cover
         */
        .cover {
          padding: 0 1.5rem;
        }
        .cover .btn-lg {
          padding: .75rem 1.25rem;
          font-weight: 700;
        }


        /*
         * Footer
         */
        .mastfoot {
          color: rgba(255, 255, 255, .5);
        }
    </style>

    {% if title %}
        <title>Short My Url Baby - {{ title }}</title>
    {% else %}
        <title>Short My Url Baby</title>
    {% endif %}
</head>
<body class="text-center">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
      </header>

      <main role="main" class="inner cover">
      <h1 class="cover-heading"><a href="{% url "home-view" %}">Short My Url Baby</a></h1>
        <div class="lead">
            {% if messages %}
                {% for message in messages %}
                    <div class="my2-4">
                        <p>
                            {{ message }}
                        </p>
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p><a href="https://tobked.github.io/">Tobiasz Kędzierski</a></p>
        </div>
      </footer>

    </div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
{% block script %} {% endblock script %}
</body>
</html>

shortener/templates/shortener/home.html
{% extends "shortener/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div>
        <form method="POST" class="form-inline">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>

            <div class="form-group">
                <button class="btn btn-secondary ml-3" type="submit">Make It Short !!!</button>
            </div>
        </form>
    </div>

{% endblock content %}

shortener/templates/shortener/link_details.html
{% extends "shortener/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div>
        <form class="form-inline">
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>

            <div class="form-group">
                <button id="copy" class="btn btn-secondary ml-3" type="button">Copy</button>
            </div>
        </form>
    </div>

{% endblock content %}

{% block script %}
    <script>
        /* source: https://css-tricks.com/native-browser-copy-clipboard/ */
        var copyURLButton = document.querySelector('#copy');
        copyURLButton.addEventListener('click', function (event) {
            var url = document.querySelector('#id_url');
            var range = document.createRange();
            range.selectNode(url);
            window.getSelection().addRange(range);

            try {
                var successful = document.execCommand('copy');
                var msg = successful ? 'successful' : 'unsuccessful';
                console.log('Copy url command was ' + msg);
            } catch (err) {
                console.log('Oops, unable to copy');
            }
            window.getSelection().removeAllRanges();
        });
    </script>
{% endblock script %}